import streamlit as st
import pandas as pd
import sys
import os

# Add project root to path
sys.path.append(os.getcwd())

from src.unit_ops import ParametricOps, VesselLibrary
from src.inventory import Inventory
import src.upstream as up

st.set_page_config(page_title="cell_OS Workflow Visualizer", layout="wide")

st.title("cell_OS Workflow Visualizer")
st.markdown("Explore the parametric operations and costs for different workflows.")

# Initialize System
@st.cache_resource
def load_system():
    vessels = VesselLibrary("data/raw/vessels.yaml")
    inv = Inventory("data/raw/pricing.yaml")
    ops = ParametricOps(vessels, inv)
    
    # Inject mock vessels for visualization
    ops.vessels.vessels["cloning_tube_1"] = vessels.get("flask_t25") # Mock
    ops.vessels.vessels["virus_flask_1"] = vessels.get("flask_t175") # Mock
    
    return ops

ops = load_system()

# Sidebar Selection
workflow_type = st.sidebar.selectbox(
    "Select Workflow",
    ["Zombie POSH (Standard)", "Vanilla POSH (Legacy)", "Upstream (Genetic Supply Chain)"]
)

recipe = None

if workflow_type == "Zombie POSH (Standard)":
    st.sidebar.header("Parameters")
    num_grnas = st.sidebar.number_input("Library Size (gRNAs)", 100, 100000, 1000)
    multimodal = st.sidebar.checkbox("Multimodal (FISH+IBEX)", False)
    automated = st.sidebar.checkbox("Automated Liquid Handling", False)
    
    recipe = ops.get_zombie_posh_complete_recipe(
        num_grnas=num_grnas,
        multimodal=multimodal,
        automated=automated,
        vessel="plate_6well"
    )

elif workflow_type == "Vanilla POSH (Legacy)":
    st.sidebar.header("Parameters")
    num_grnas = st.sidebar.number_input("Library Size (gRNAs)", 100, 100000, 1000)
    automated = st.sidebar.checkbox("Automated Liquid Handling", False)
    
    recipe = ops.get_vanilla_posh_complete_recipe(
        num_grnas=num_grnas,
        automated=automated,
        vessel="plate_96well"
    )

elif workflow_type == "Upstream (Genetic Supply Chain)":
    st.sidebar.header("Parameters")
    num_genes = st.sidebar.number_input("Number of Genes", 10, 5000, 100)
    vendor = st.sidebar.selectbox("Oligo Vendor", ["Twist Bioscience", "GenScript"])
    
    # Create mock design
    genes = [up.GeneTarget(f"GENE_{i}", f"ID_{i}") for i in range(num_genes)]
    design = up.LibraryDesign(f"Design_{num_genes}", genes)
    
    recipe = ops.get_upstream_workflow_recipe(
        design=design,
        vendor=vendor,
        cloning_vessel="cloning_tube_1",
        virus_vessel="virus_flask_1"
    )

# Visualization
if recipe:
    st.header(f"Workflow: {recipe.name}")
    
    # Calculate Score
    # We need a dummy library for derive_score, or we can just sum manually
    # derive_score expects a UnitOpLibrary, which we don't have fully populated with all ops
    # But AssayRecipe.derive_score handles UnitOp objects directly too.
    # Let's mock a library
    class MockLib:
        def get(self, x): return None
    
    score = recipe.derive_score(MockLib())
    
    # Metrics
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Material Cost", f"${score.total_usd:.2f}")
    col2.metric("Time Score", score.total_time_score)
    col3.metric("Cost Score", score.total_cost_score)
    col4.metric("Bottleneck", score.bottleneck_instrument)
    
    st.divider()
    
    # Layers
    for layer_name, steps in recipe.layers.items():
        st.subheader(f"Layer: {layer_name.replace('_', ' ').title()}")
        
        # Create DataFrame for steps
        step_data = []
        for item, count in steps:
            if hasattr(item, "name"):
                uo = item
                step_data.append({
                    "Step Name": uo.name,
                    "Count": count,
                    "Category": uo.category,
                    "Instrument": uo.instrument,
                    "Material Cost ($)": f"${uo.material_cost_usd * count:.2f}",
                    "Instrument Cost ($)": f"${uo.instrument_cost_usd * count:.2f}",
                    "Time Score": uo.time_score * count
                })
            else:
                step_data.append({"Step Name": str(item), "Count": count})
        
        df = pd.DataFrame(step_data)
        st.dataframe(df, use_container_width=True)
        
    st.divider()
    st.caption("Generated by cell_OS Workflow Visualizer")
