import streamlit as st
import pandas as pd
import plotly.express as px
from dashboard_app.pages.tab_campaign_posh.components.moa_classifier import classify_and_render_moa

def render_embeddings(s_result):
    """Render the Embeddings tab content."""
    if hasattr(s_result, "embeddings") and not s_result.embeddings.empty:
        st.markdown("### Deep Learning Embeddings (128-d)")
        st.markdown("High-dimensional phenotypic profiles generated by a simulated Deep Learning encoder (e.g., DINO). Each cell is represented as a 128-dimensional vector.")
        
        # 1. UMAP Plot
        st.markdown("#### Phenotypic Landscape (UMAP)")
        
        # Merge with volcano data to get phenotype info
        if not s_result.volcano_data.empty:
            df_umap = pd.merge(s_result.projection_2d, s_result.volcano_data[["Gene", "Log2FoldChange", "P_Value"]], on="Gene")
            
            # Create a "Phenotype" column for coloring
            df_umap["Phenotype"] = "Control-like"
            # Identify hits (using same criteria as volcano plot usually does, or just checking hit list)
            hit_genes = s_result.hit_list["Gene"].tolist() if not s_result.hit_list.empty else []
            df_umap.loc[df_umap["Gene"].isin(hit_genes), "Phenotype"] = "Hit"
            
            # Create numeric size column
            df_umap["Size"] = 2.0
            df_umap.loc[df_umap["Phenotype"] == "Hit", "Size"] = 5.0
            
            fig_umap = px.scatter(
                df_umap,
                x="UMAP_1",
                y="UMAP_2",
                color="Phenotype",
                hover_data=["Gene", "Log2FoldChange"],
                title="UMAP Projection of Phenotypic Space",
                color_discrete_map={"Control-like": "lightgray", "Hit": "#FF4B4B"},
                opacity=0.7,
                size="Size", 
                size_max=10,
                symbol="Phenotype"
            )
            st.plotly_chart(fig_umap, use_container_width=True, key="umap_plot")
            
            st.info("💡 **Interpretation:** In this 2D projection of the 128-dimensional space, points that cluster together share similar phenotypes. 'Hits' (red) form distinct clusters away from the 'Control-like' population, indicating they have perturbed the cell state in a specific way.")
            
            # Mechanism of Action Classification
            classify_and_render_moa(s_result, df_umap)
            
            # Embedding Heatmap (Sample)
            st.markdown("---")
            st.markdown("#### Embedding Vectors (Sample)")
            st.markdown("Visualizing the raw 128-dimensional vectors for top hits vs controls.")
            
            if not s_result.hit_list.empty:
                top_hits = s_result.hit_list.head(5)["Gene"].tolist()
                controls = s_result.volcano_data[~s_result.volcano_data["Gene"].isin(hit_genes)].head(5)["Gene"].tolist()
                
                sample_genes = top_hits + controls
                sample_embeds = s_result.embeddings[s_result.embeddings["Gene"].isin(sample_genes)].set_index("Gene")
                
                # Filter only DIM columns
                dim_cols = [c for c in sample_embeds.columns if c.startswith("DIM_")]
                sample_embeds = sample_embeds[dim_cols]
                
                fig_heat = px.imshow(
                    sample_embeds,
                    labels=dict(x="Embedding Dimension", y="Gene", color="Activation"),
                    title="Deep Learning Feature Activations",
                    aspect="auto",
                    color_continuous_scale="Viridis"
                )
                st.plotly_chart(fig_heat, use_container_width=True, key="embed_heatmap")
        
    else:
        st.info("No embedding data available. Run a new simulation to generate embeddings.")
